{{- range $key, $value := index .Values "external-secrets" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $key }}
  namespace: {{ $.Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ $value.secretStoreRef }}
    kind: ClusterSecretStore
  refreshInterval: {{ default "1h" $value.refreshInterval }}
  {{- if $value.template }}
  target:
    creationPolicy: Owner
    template:
      {{- toYaml $value.template | nindent 8 }}
  {{- end }}
  {{- if $value.data }}
  data:
    {{- toYaml $value.data | nindent 4 }}
  {{- end }}
  {{- if $value.dataFrom }}
  dataFrom:
    {{- toYaml .dataFrom | nindent 2 }}
  {{- end }}
{{- end }}
